services:
  elasticsearch:
    container_name: elastic
    image: elasticsearch:8.15.3
    environment:
      - TZ=Africa/Kampala 
      # Or you can use HV time 
      #- /etc/localtime:/etc/localtime:ro
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - elk-net
    ports:
      - 9200:9200
  kibana:
    container_name: kibana
    image: kibana:8.15.3
    environment:
      - TZ=Africa/Kampala 
      # Or you can use HV time 
      #- /etc/localtime:/etc/localtime:ro
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    networks:
      - elk-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
networks:
  elk-net:
    driver: bridge
